version: '3.7'

services:

  traefik:
    image: traefik:1.7-alpine
    command: --docker --docker.exposedbydefault=false --api
    ports:
        - "127.0.0.1:80:80"
        - "127.0.0.1:8080:8080"
        - "127.0.0.1:443:443"
    labels:
      - traefik.frontend.rule=Host:monitor.dev.docker
    volumes:
      - /run/docker.sock:/var/run/docker.sock
      - ./config/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./certs/self.crt:/etc/ssl/self.crt
      - ./certs/self.key:/etc/ssl/self.key
    networks:
      proxy:
        ipv4_address: 172.20.0.2
    restart: always

networks:
  proxy:
    external: true
